// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _flavor =
      String.fromEnvironment('FLAVOR', defaultValue: 'user');

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'PSgy does not support Web. Build for iOS or Android only.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _flavor == 'coach' ? androidCoach : androidUser;
      case TargetPlatform.iOS:
        return _flavor == 'coach' ? iosCoach : iosUser;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'PSgy supports iOS and Android only.',
        );
      default:
        throw UnsupportedError(
          'PSgy supports iOS and Android only.',
        );
    }
  }

  static const FirebaseOptions androidUser = FirebaseOptions(
    apiKey: 'AIzaSyBznGpf-NWcx3-1d1h8l3YAsoHkZrRAHQI',
    appId: '1:656165291904:android:497dadb4986c505a41e365',
    messagingSenderId: '656165291904',
    projectId: 'psgy-app',
    storageBucket: 'psgy-app.firebasestorage.app',
  );

  static const FirebaseOptions androidCoach = FirebaseOptions(
    apiKey: 'AIzaSyBznGpf-NWcx3-1d1h8l3YAsoHkZrRAHQI',
    appId: '1:656165291904:android:6566064ff773778841e365',
    messagingSenderId: '656165291904',
    projectId: 'psgy-app',
    storageBucket: 'psgy-app.firebasestorage.app',
  );

  /// Legacy single-app Android config (com.psgy.user).
  static const FirebaseOptions android = androidUser;

  static const FirebaseOptions iosUser = FirebaseOptions(
    apiKey: 'AIzaSyDGLuhSd_Tr6UkO0a27XQ7yZN_6XmRVxF4',
    appId: '1:656165291904:ios:c1d28b926b942d7541e365',
    messagingSenderId: '656165291904',
    projectId: 'psgy-app',
    storageBucket: 'psgy-app.firebasestorage.app',
    iosBundleId: 'com.psgy.user',
  );

  static const FirebaseOptions iosCoach = FirebaseOptions(
    apiKey: 'AIzaSyDGLuhSd_Tr6UkO0a27XQ7yZN_6XmRVxF4',
    appId: '1:656165291904:ios:ba13f202ed0a08f241e365',
    messagingSenderId: '656165291904',
    projectId: 'psgy-app',
    storageBucket: 'psgy-app.firebasestorage.app',
    iosBundleId: 'com.psgy.coach',
  );
}
