// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _flavor =
      String.fromEnvironment('FLAVOR', defaultValue: 'user');

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'ParkingLink does not support Web. Build for iOS or Android only.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _flavor == 'staff' ? androidStaff : androidUser;
      case TargetPlatform.iOS:
        return _flavor == 'staff' ? iosStaff : iosUser;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'ParkingLink supports iOS and Android only.',
        );
      default:
        throw UnsupportedError(
          'ParkingLink supports iOS and Android only.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNCSiApiP9BPpbfOts1Elk52AqBsnSQVk',
    appId: '1:259032555472:web:56edf53dc655a1ea5063d5',
    messagingSenderId: '259032555472',
    projectId: 'parkinglink-v2',
    authDomain: 'parkinglink-v2.firebaseapp.com',
    storageBucket: 'parkinglink-v2.firebasestorage.app',
    measurementId: 'G-M5RFPSL4NQ',
  );

  static const FirebaseOptions androidUser = FirebaseOptions(
    apiKey: 'AIzaSyDrnRAeuuci3q5Y0blVeY-ZYY_yIGpGsVc',
    appId: '1:259032555472:android:c4ef7b8321b561f45063d5',
    messagingSenderId: '259032555472',
    projectId: 'parkinglink-v2',
    storageBucket: 'parkinglink-v2.firebasestorage.app',
  );

  static const FirebaseOptions androidStaff = FirebaseOptions(
    apiKey: 'AIzaSyDrnRAeuuci3q5Y0blVeY-ZYY_yIGpGsVc',
    appId: '1:259032555472:android:10fa5e8d7a15353b5063d5',
    messagingSenderId: '259032555472',
    projectId: 'parkinglink-v2',
    storageBucket: 'parkinglink-v2.firebasestorage.app',
  );

  /// Legacy single-app Android config (com.parkinglink).
  static const FirebaseOptions android = androidUser;

  static const FirebaseOptions iosUser = FirebaseOptions(
    apiKey: 'AIzaSyDZR0rs3Ifzuo3TBf8Ua7nTXioC3ToB5iE',
    appId: '1:259032555472:ios:ba0ac2791012cc805063d5',
    messagingSenderId: '259032555472',
    projectId: 'parkinglink-v2',
    storageBucket: 'parkinglink-v2.firebasestorage.app',
    iosBundleId: 'com.parkinglink.user',
  );

  static const FirebaseOptions iosStaff = FirebaseOptions(
    apiKey: 'AIzaSyDZR0rs3Ifzuo3TBf8Ua7nTXioC3ToB5iE',
    appId: '1:259032555472:ios:2ecc96250348c4955063d5',
    messagingSenderId: '259032555472',
    projectId: 'parkinglink-v2',
    storageBucket: 'parkinglink-v2.firebasestorage.app',
    iosBundleId: 'com.parkinglink.staff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZR0rs3Ifzuo3TBf8Ua7nTXioC3ToB5iE',
    appId: '1:259032555472:ios:e444f6506e618dbf5063d5',
    messagingSenderId: '259032555472',
    projectId: 'parkinglink-v2',
    storageBucket: 'parkinglink-v2.firebasestorage.app',
    iosBundleId: 'com.parkinglink.parkingLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNCSiApiP9BPpbfOts1Elk52AqBsnSQVk',
    appId: '1:259032555472:web:3f3c6a0d1bedf4745063d5',
    messagingSenderId: '259032555472',
    projectId: 'parkinglink-v2',
    authDomain: 'parkinglink-v2.firebaseapp.com',
    storageBucket: 'parkinglink-v2.firebasestorage.app',
    measurementId: 'G-TVCL34S678',
  );
}
