#!/usr/bin/env bash
# Create Android release keystore + android/key.properties for ParkingLink.
#
# Usage:
#   ./scripts/create_android_release_keystore.sh              # interactive (production)
#   ./scripts/create_android_release_keystore.sh --dev        # non-interactive dev keystore
#
# Production (recommended before Play Store upload):
#   ./scripts/create_android_release_keystore.sh ~/secure/parkinglink-release.jks parkinglink
#
set -euo pipefail

KEYTOOL="keytool"
if [[ -x "/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/keytool" ]]; then
  KEYTOOL="/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/keytool"
elif ! command -v keytool >/dev/null 2>&1; then
  echo "error: keytool not found. Install Android Studio or JDK." >&2
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
KEYSTORE_DIR="${ROOT_DIR}/android/keystores"
KEYSTORE_PATH="${1:-${KEYSTORE_DIR}/parkinglink-release.jks}"
ALIAS="${2:-parkinglink}"
KEY_PROPERTIES="${ROOT_DIR}/android/key.properties"
DEV_MODE=false

if [[ "${1:-}" == "--dev" ]]; then
  DEV_MODE=true
  KEYSTORE_PATH="${KEYSTORE_DIR}/parkinglink-release.jks"
  ALIAS="parkinglink"
fi

mkdir -p "${KEYSTORE_DIR}"

if [[ -f "${KEYSTORE_PATH}" ]]; then
  echo "Keystore already exists: ${KEYSTORE_PATH}"
else
  if [[ "${DEV_MODE}" == true ]]; then
    echo "Creating DEV release keystore (non-interactive) at: ${KEYSTORE_PATH}"
    "${KEYTOOL}" -genkeypair -v \
      -storetype PKCS12 \
      -keystore "${KEYSTORE_PATH}" \
      -alias "${ALIAS}" \
      -keyalg RSA -keysize 2048 -validity 10000 \
      -storepass "parkinglink_dev_store" \
      -keypass "parkinglink_dev_key" \
      -dname "CN=ParkingLink Dev, OU=Mobile, O=ParkingLink, L=Ho Chi Minh, ST=HCM, C=VN"
    STORE_PASSWORD="parkinglink_dev_store"
    KEY_PASSWORD="parkinglink_dev_store"
  else
    echo "Creating PRODUCTION release keystore at: ${KEYSTORE_PATH}"
    "${KEYTOOL}" -genkey -v \
      -keystore "${KEYSTORE_PATH}" \
      -keyalg RSA -keysize 2048 -validity 10000 \
      -alias "${ALIAS}"
    echo ""
    read -r -s -p "Enter keystore password again for key.properties: " STORE_PASSWORD
    echo ""
    read -r -s -p "Enter key password (Enter if same as keystore): " KEY_PASSWORD
    echo ""
    KEY_PASSWORD="${KEY_PASSWORD:-$STORE_PASSWORD}"
  fi
fi

# Resolve storeFile path relative to android/ (Gradle rootProject)
if [[ "${KEYSTORE_PATH}" == "${KEYSTORE_DIR}/"* ]]; then
  RELATIVE_STORE_FILE="keystores/$(basename "${KEYSTORE_PATH}")"
else
  RELATIVE_STORE_FILE="${KEYSTORE_PATH}"
fi

if [[ "${DEV_MODE}" == true ]]; then
  STORE_PASSWORD="parkinglink_dev_store"
  KEY_PASSWORD="parkinglink_dev_key"
fi

if [[ -z "${STORE_PASSWORD:-}" ]]; then
  read -r -s -p "Store password for key.properties: " STORE_PASSWORD
  echo ""
  read -r -s -p "Key password for key.properties: " KEY_PASSWORD
  echo ""
  KEY_PASSWORD="${KEY_PASSWORD:-$STORE_PASSWORD}"
fi

cat > "${KEY_PROPERTIES}" <<EOF
# Generated by scripts/create_android_release_keystore.sh — DO NOT COMMIT
storePassword=${STORE_PASSWORD}
keyPassword=${KEY_PASSWORD}
keyAlias=${ALIAS}
storeFile=${RELATIVE_STORE_FILE}
EOF

chmod 600 "${KEY_PROPERTIES}" 2>/dev/null || true

echo ""
echo "✓ Keystore: ${KEYSTORE_PATH}"
echo "✓ key.properties: ${KEY_PROPERTIES}"
echo ""
echo "Build production AAB:"
echo "  flutter build appbundle --flavor user --release --dart-define=FLAVOR=user --dart-define=ENV=production"
echo "  flutter build appbundle --flavor staff --release --dart-define=FLAVOR=staff --dart-define=ENV=production"
